name: Build IJKPlayer for Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with debug logging'
        required: false
        default: false
      skip_long_steps:
        type: boolean
        description: 'Skip time-consuming steps for faster debugging'
        required: false
        default: false

env:
  NDK_VERSION: r10e
  GRADLE_VERSION: 6.7.1

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git yasm build-essential curl unzip
    
    - name: Setup Android NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux-x86_64.zip
        unzip -q android-ndk-${{ env.NDK_VERSION }}-linux-x86_64.zip
        rm android-ndk-${{ env.NDK_VERSION }}-linux-x86_64.zip
        echo "ANDROID_NDK_ROOT=$PWD/android-ndk-${{ env.NDK_VERSION }}" >> $GITHUB_ENV
        echo "ANDROID_NDK=$PWD/android-ndk-${{ env.NDK_VERSION }}" >> $GITHUB_PATH

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Configure environment
      run: |
        echo "PATH=$ANDROID_NDK_ROOT:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools:$PATH" >> $GITHUB_ENV
        echo "SHELL=/bin/bash" >> $GITHUB_ENV
      
    - name: Clone IJKPlayer
      run: git clone https://github.com/zero16832/ijkplayer.git ijkplayer-android
      
    - name: Initialize IJKPlayer
      if: ${{ !github.event.inputs.skip_long_steps }}
      working-directory: ijkplayer-android
      run: |
        ./init-android.sh
        ./init-android-openssl.sh
        
    - name: Build OpenSSL
      if: ${{ !github.event.inputs.skip_long_steps }}
      working-directory: ijkplayer-android/android/contrib
      run: |
        export ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT
        export ANDROID_NDK=$ANDROID_NDK
        bash ./compile-openssl.sh clean
        bash ./compile-openssl.sh all
        
    - name: Build FFmpeg
      if: ${{ !github.event.inputs.skip_long_steps }}
      working-directory: ijkplayer-android/android/contrib
      run: |
        export ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT
        export ANDROID_NDK=$ANDROID_NDK
        bash ./compile-ffmpeg.sh clean
        bash ./compile-ffmpeg.sh all
        
    - name: Build IJKPlayer
      if: ${{ !github.event.inputs.skip_long_steps }}
      working-directory: ijkplayer-android
      run: |
        export ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT
        export ANDROID_NDK=$ANDROID_NDK
        cd android
        bash ./compile-ijk.sh all
        
    - name: Update Gradle Wrapper
      working-directory: ijkplayer-android/android/ijkplayer
      run: |
        wget https://services.gradle.org/distributions/gradle-${{ env.GRADLE_VERSION }}-bin.zip
        unzip -d /opt/gradle gradle-${{ env.GRADLE_VERSION }}-bin.zip
        echo "GRADLE_HOME=/opt/gradle/gradle-${{ env.GRADLE_VERSION }}" >> $GITHUB_ENV
        echo "/opt/gradle/gradle-${{ env.GRADLE_VERSION }}/bin" >> $GITHUB_PATH
        gradle wrapper --gradle-version ${{ env.GRADLE_VERSION }}

    - name: Update build.gradle files
      working-directory: ijkplayer-android/android/ijkplayer
      run: |
        sed -i 's/com\.android\.tools\.build:gradle:1\.2\.3/com.android.tools.build:gradle:3.6.4/' build.gradle
        sed -i 's/com\.github\.dcendents:android-maven-plugin:1\.2/com.github.dcendents:android-maven-gradle-plugin:2.1/' build.gradle
        sed -i 's/classpath "com\.jfrog\.bintray\.gradle:gradle-bintray-plugin:1\.7\.3"//' build.gradle

    - name: Build Sample
      working-directory: ijkplayer-android/android/ijkplayer
      run: |
        chmod +x ./gradlew
        ./gradlew build
        
    - name: Upload IJKPlayer libraries
      if: ${{ !github.event.inputs.skip_long_steps }}
      uses: actions/upload-artifact@v3
      with:
        name: ijkplayer-android-libs
        path: ijkplayer-android/android/ijkplayer/ijkplayer-*/build/outputs/aar/*.aar
        if-no-files-found: error

    - name: Upload Sample APK
      uses: actions/upload-artifact@v3
      with:
        name: ijkplayer-sample-apk
        path: ijkplayer-android/android/ijkplayer/ijkplayer-example/build/outputs/apk/debug/ijkplayer-example-debug.apk
        if-no-files-found: error
