name: Build IJKPlayer for Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  NDK_VERSION: r10e

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git yasm build-essential curl unzip

    - name: Cache Android NDK
      id: cache-ndk
      uses: actions/cache@v3
      with:
        path: android-ndk-${{ env.NDK_VERSION }}
        key: ${{ runner.os }}-ndk-${{ env.NDK_VERSION }}
    
    - name: Setup Android NDK
      if: steps.cache-ndk.outputs.cache-hit != 'true'
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux-x86_64.zip
        unzip -q android-ndk-${{ env.NDK_VERSION }}-linux-x86_64.zip
        rm android-ndk-${{ env.NDK_VERSION }}-linux-x86_64.zip
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Configure environment
      run: |
        echo "ANDROID_NDK=$PWD/android-ndk-${{ env.NDK_VERSION }}" >> $GITHUB_ENV
        echo "$PWD/android-ndk-${{ env.NDK_VERSION }}" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/tools" >> $GITHUB_PATH
      
    - name: Clone IJKPlayer
      run: git clone https://github.com/zero16832/ijkplayer.git ijkplayer-android
      
    - name: Initialize IJKPlayer
      working-directory: ijkplayer-android
      run: |
        ./init-android.sh
        ./init-android-openssl.sh
        
    - name: Build OpenSSL
      working-directory: ijkplayer-android/android/contrib
      run: |
        ./compile-openssl.sh clean
        ./compile-openssl.sh all
        
    - name: Build FFmpeg
      working-directory: ijkplayer-android/android/contrib
      run: |
        ./compile-ffmpeg.sh clean
        ./compile-ffmpeg.sh all
        
    - name: Build IJKPlayer
      working-directory: ijkplayer-android
      run: |
        cd android
        ./compile-ijk.sh all
        
    - name: Build Sample
      working-directory: ijkplayer-android/android/ijkplayer
      run: |
        ./gradlew wrapper --gradle-version=6.7.1
        ./gradlew build
        
    - name: Upload IJKPlayer libraries
      uses: actions/upload-artifact@v3
      with:
        name: ijkplayer-android-libs
        path: ijkplayer-android/android/ijkplayer/ijkplayer-*/build/outputs/aar/*.aar
        if-no-files-found: error

    - name: Upload Sample APK
      uses: actions/upload-artifact@v3
      with:
        name: ijkplayer-sample-apk
        path: ijkplayer-android/android/ijkplayer/ijkplayer-example/build/outputs/apk/debug/ijkplayer-example-debug.apk
        if-no-files-found: error
